import Vue from 'vue'
import { wrapFunctional } from './utils'

const components = {
  ActiveTokyoAlert: () => import('../../components/ActiveTokyoAlert.vue' /* webpackChunkName: "components/active-tokyo-alert" */).then(c => wrapFunctional(c.default || c)),
  AgencyBarChart: () => import('../../components/AgencyBarChart.vue' /* webpackChunkName: "components/agency-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  AppLink: () => import('../../components/AppLink.vue' /* webpackChunkName: "components/app-link" */).then(c => wrapFunctional(c.default || c)),
  CardsLazyRow: () => import('../../components/CardsLazyRow.vue' /* webpackChunkName: "components/cards-lazy-row" */).then(c => wrapFunctional(c.default || c)),
  CardsMonitoring: () => import('../../components/CardsMonitoring.vue' /* webpackChunkName: "components/cards-monitoring" */).then(c => wrapFunctional(c.default || c)),
  CardsReference: () => import('../../components/CardsReference.vue' /* webpackChunkName: "components/cards-reference" */).then(c => wrapFunctional(c.default || c)),
  CardsTab: () => import('../../components/CardsTab.vue' /* webpackChunkName: "components/cards-tab" */).then(c => wrapFunctional(c.default || c)),
  ConfirmedCasesByMunicipalitiesTable: () => import('../../components/ConfirmedCasesByMunicipalitiesTable.vue' /* webpackChunkName: "components/confirmed-cases-by-municipalities-table" */).then(c => wrapFunctional(c.default || c)),
  ConfirmedCasesDetailsTable: () => import('../../components/ConfirmedCasesDetailsTable.vue' /* webpackChunkName: "components/confirmed-cases-details-table" */).then(c => wrapFunctional(c.default || c)),
  Consultation: () => import('../../components/Consultation.vue' /* webpackChunkName: "components/consultation" */).then(c => wrapFunctional(c.default || c)),
  DashedRectangleTimeBarChart: () => import('../../components/DashedRectangleTimeBarChart.vue' /* webpackChunkName: "components/dashed-rectangle-time-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  DataSelector: () => import('../../components/DataSelector.vue' /* webpackChunkName: "components/data-selector" */).then(c => wrapFunctional(c.default || c)),
  DataTable: () => import('../../components/DataTable.vue' /* webpackChunkName: "components/data-table" */).then(c => wrapFunctional(c.default || c)),
  DataView: () => import('../../components/DataView.vue' /* webpackChunkName: "components/data-view" */).then(c => wrapFunctional(c.default || c)),
  DataViewCustomInfoPanel: () => import('../../components/DataViewCustomInfoPanel.vue' /* webpackChunkName: "components/data-view-custom-info-panel" */).then(c => wrapFunctional(c.default || c)),
  DataViewDataSetPanel: () => import('../../components/DataViewDataSetPanel.vue' /* webpackChunkName: "components/data-view-data-set-panel" */).then(c => wrapFunctional(c.default || c)),
  DataViewExpantionPanel: () => import('../../components/DataViewExpantionPanel.vue' /* webpackChunkName: "components/data-view-expantion-panel" */).then(c => wrapFunctional(c.default || c)),
  DataViewShare: () => import('../../components/DataViewShare.vue' /* webpackChunkName: "components/data-view-share" */).then(c => wrapFunctional(c.default || c)),
  DataViewTable: () => import('../../components/DataViewTable.vue' /* webpackChunkName: "components/data-view-table" */).then(c => wrapFunctional(c.default || c)),
  DevelopmentModeMark: () => import('../../components/DevelopmentModeMark.vue' /* webpackChunkName: "components/development-mode-mark" */).then(c => wrapFunctional(c.default || c)),
  FeverMixedChart: () => import('../../components/FeverMixedChart.vue' /* webpackChunkName: "components/fever-mixed-chart" */).then(c => wrapFunctional(c.default || c)),
  InfectionMedicalcareprovisionStatus: () => import('../../components/InfectionMedicalcareprovisionStatus.vue' /* webpackChunkName: "components/infection-medicalcareprovision-status" */).then(c => wrapFunctional(c.default || c)),
  LanguageSelector: () => import('../../components/LanguageSelector.vue' /* webpackChunkName: "components/language-selector" */).then(c => wrapFunctional(c.default || c)),
  LinkToInformationAboutEmergencyMeasure: () => import('../../components/LinkToInformationAboutEmergencyMeasure.vue' /* webpackChunkName: "components/link-to-information-about-emergency-measure" */).then(c => wrapFunctional(c.default || c)),
  MenuList: () => import('../../components/MenuList.vue' /* webpackChunkName: "components/menu-list" */).then(c => wrapFunctional(c.default || c)),
  MetroBarChart: () => import('../../components/MetroBarChart.vue' /* webpackChunkName: "components/metro-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  MixedBarAndLineChart: () => import('../../components/MixedBarAndLineChart.vue' /* webpackChunkName: "components/mixed-bar-and-line-chart" */).then(c => wrapFunctional(c.default || c)),
  MonitoringCommentCard: () => import('../../components/MonitoringCommentCard.vue' /* webpackChunkName: "components/monitoring-comment-card" */).then(c => wrapFunctional(c.default || c)),
  MonitoringCommentCardImageSwipe: () => import('../../components/MonitoringCommentCardImageSwipe.vue' /* webpackChunkName: "components/monitoring-comment-card-image-swipe" */).then(c => wrapFunctional(c.default || c)),
  MonitoringCommentFrame: () => import('../../components/MonitoringCommentFrame.vue' /* webpackChunkName: "components/monitoring-comment-frame" */).then(c => wrapFunctional(c.default || c)),
  MonitoringConfirmedCasesChart: () => import('../../components/MonitoringConfirmedCasesChart.vue' /* webpackChunkName: "components/monitoring-confirmed-cases-chart" */).then(c => wrapFunctional(c.default || c)),
  MonitoringConsultationDeskReportChart: () => import('../../components/MonitoringConsultationDeskReportChart.vue' /* webpackChunkName: "components/monitoring-consultation-desk-report-chart" */).then(c => wrapFunctional(c.default || c)),
  MonitoringItemsOverviewTableInfectionStatus: () => import('../../components/MonitoringItemsOverviewTableInfectionStatus.vue' /* webpackChunkName: "components/monitoring-items-overview-table-infection-status" */).then(c => wrapFunctional(c.default || c)),
  MonitoringItemsOverviewTableMedicalSystem: () => import('../../components/MonitoringItemsOverviewTableMedicalSystem.vue' /* webpackChunkName: "components/monitoring-items-overview-table-medical-system" */).then(c => wrapFunctional(c.default || c)),
  MonitoringItemsOverviewTableValueWithTranslatableUnit: () => import('../../components/MonitoringItemsOverviewTableValueWithTranslatableUnit.vue' /* webpackChunkName: "components/monitoring-items-overview-table-value-with-translatable-unit" */).then(c => wrapFunctional(c.default || c)),
  NoScript: () => import('../../components/NoScript.vue' /* webpackChunkName: "components/no-script" */).then(c => wrapFunctional(c.default || c)),
  OpenDataLink: () => import('../../components/OpenDataLink.vue' /* webpackChunkName: "components/open-data-link" */).then(c => wrapFunctional(c.default || c)),
  PageHeader: () => import('../../components/PageHeader.vue' /* webpackChunkName: "components/page-header" */).then(c => wrapFunctional(c.default || c)),
  PositiveRateMixedChart: () => import('../../components/PositiveRateMixedChart.vue' /* webpackChunkName: "components/positive-rate-mixed-chart" */).then(c => wrapFunctional(c.default || c)),
  PrinterButton: () => import('../../components/PrinterButton.vue' /* webpackChunkName: "components/printer-button" */).then(c => wrapFunctional(c.default || c)),
  ScrollableChart: () => import('../../components/ScrollableChart.vue' /* webpackChunkName: "components/scrollable-chart" */).then(c => wrapFunctional(c.default || c)),
  SevereCaseBarChart: () => import('../../components/SevereCaseBarChart.vue' /* webpackChunkName: "components/severe-case-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  SideNavigation: () => import('../../components/SideNavigation.vue' /* webpackChunkName: "components/side-navigation" */).then(c => wrapFunctional(c.default || c)),
  SiteTopUpper: () => import('../../components/SiteTopUpper.vue' /* webpackChunkName: "components/site-top-upper" */).then(c => wrapFunctional(c.default || c)),
  StaticCard: () => import('../../components/StaticCard.vue' /* webpackChunkName: "components/static-card" */).then(c => wrapFunctional(c.default || c)),
  StaticInfo: () => import('../../components/StaticInfo.vue' /* webpackChunkName: "components/static-info" */).then(c => wrapFunctional(c.default || c)),
  StayingPopulation: () => import('../../components/StayingPopulation.vue' /* webpackChunkName: "components/staying-population" */).then(c => wrapFunctional(c.default || c)),
  TimeBarChart: () => import('../../components/TimeBarChart.vue' /* webpackChunkName: "components/time-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  TimeStackedBarChart: () => import('../../components/TimeStackedBarChart.vue' /* webpackChunkName: "components/time-stacked-bar-chart" */).then(c => wrapFunctional(c.default || c)),
  TokyoAlertCard: () => import('../../components/TokyoAlertCard.vue' /* webpackChunkName: "components/tokyo-alert-card" */).then(c => wrapFunctional(c.default || c)),
  UntrackedRateMixedChart: () => import('../../components/UntrackedRateMixedChart.vue' /* webpackChunkName: "components/untracked-rate-mixed-chart" */).then(c => wrapFunctional(c.default || c)),
  WhatsNew: () => import('../../components/WhatsNew.vue' /* webpackChunkName: "components/whats-new" */).then(c => wrapFunctional(c.default || c)),
  CardsAgencyCard: () => import('../../components/cards/AgencyCard.vue' /* webpackChunkName: "components/cards-agency-card" */).then(c => wrapFunctional(c.default || c)),
  CardsCardRow: () => import('../../components/cards/CardRow.vue' /* webpackChunkName: "components/cards-card-row" */).then(c => wrapFunctional(c.default || c)),
  CardsConfirmedCasesAttributesCard: () => import('../../components/cards/ConfirmedCasesAttributesCard.vue' /* webpackChunkName: "components/cards-confirmed-cases-attributes-card" */).then(c => wrapFunctional(c.default || c)),
  CardsConfirmedCasesByMunicipalitiesCard: () => import('../../components/cards/ConfirmedCasesByMunicipalitiesCard.vue' /* webpackChunkName: "components/cards-confirmed-cases-by-municipalities-card" */).then(c => wrapFunctional(c.default || c)),
  CardsConfirmedCasesDetailsCard: () => import('../../components/cards/ConfirmedCasesDetailsCard.vue' /* webpackChunkName: "components/cards-confirmed-cases-details-card" */).then(c => wrapFunctional(c.default || c)),
  CardsConfirmedCasesNumberCard: () => import('../../components/cards/ConfirmedCasesNumberCard.vue' /* webpackChunkName: "components/cards-confirmed-cases-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsConsultationAboutFeverNumberCard: () => import('../../components/cards/ConsultationAboutFeverNumberCard.vue' /* webpackChunkName: "components/cards-consultation-about-fever-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsDeathsByDeathDateCard: () => import('../../components/cards/DeathsByDeathDateCard.vue' /* webpackChunkName: "components/cards-deaths-by-death-date-card" */).then(c => wrapFunctional(c.default || c)),
  CardsHospitalizedNumberCard: () => import('../../components/cards/HospitalizedNumberCard.vue' /* webpackChunkName: "components/cards-hospitalized-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsMetroCard: () => import('../../components/cards/MetroCard.vue' /* webpackChunkName: "components/cards-metro-card" */).then(c => wrapFunctional(c.default || c)),
  CardsMonitoringConfirmedCasesNumberCard: () => import('../../components/cards/MonitoringConfirmedCasesNumberCard.vue' /* webpackChunkName: "components/cards-monitoring-confirmed-cases-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsMonitoringConsultationDeskReportsNumberCard: () => import('../../components/cards/MonitoringConsultationDeskReportsNumberCard.vue' /* webpackChunkName: "components/cards-monitoring-consultation-desk-reports-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsMonitoringItemsOverviewCard: () => import('../../components/cards/MonitoringItemsOverviewCard.vue' /* webpackChunkName: "components/cards-monitoring-items-overview-card" */).then(c => wrapFunctional(c.default || c)),
  CardsPositiveNumberByDevelopedDateCard: () => import('../../components/cards/PositiveNumberByDevelopedDateCard.vue' /* webpackChunkName: "components/cards-positive-number-by-developed-date-card" */).then(c => wrapFunctional(c.default || c)),
  CardsPositiveNumberByDiagnosedDateCard: () => import('../../components/cards/PositiveNumberByDiagnosedDateCard.vue' /* webpackChunkName: "components/cards-positive-number-by-diagnosed-date-card" */).then(c => wrapFunctional(c.default || c)),
  CardsPositiveRateCard: () => import('../../components/cards/PositiveRateCard.vue' /* webpackChunkName: "components/cards-positive-rate-card" */).then(c => wrapFunctional(c.default || c)),
  CardsSevereCaseCard: () => import('../../components/cards/SevereCaseCard.vue' /* webpackChunkName: "components/cards-severe-case-card" */).then(c => wrapFunctional(c.default || c)),
  CardsTelephoneAdvisoryReportsNumberCard: () => import('../../components/cards/TelephoneAdvisoryReportsNumberCard.vue' /* webpackChunkName: "components/cards-telephone-advisory-reports-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsTestedNumberCard: () => import('../../components/cards/TestedNumberCard.vue' /* webpackChunkName: "components/cards-tested-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsTokyoFeverConsultationCenterReportsNumberCard: () => import('../../components/cards/TokyoFeverConsultationCenterReportsNumberCard.vue' /* webpackChunkName: "components/cards-tokyo-fever-consultation-center-reports-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsTokyoRulesApplicationNumberCard: () => import('../../components/cards/TokyoRulesApplicationNumberCard.vue' /* webpackChunkName: "components/cards-tokyo-rules-application-number-card" */).then(c => wrapFunctional(c.default || c)),
  CardsUntrackedRateCard: () => import('../../components/cards/UntrackedRateCard.vue' /* webpackChunkName: "components/cards-untracked-rate-card" */).then(c => wrapFunctional(c.default || c))
}

for (const name in components) {
  Vue.component(name, components[name])
  Vue.component('Lazy' + name, components[name])
}
